### ISSUE TITLE
Creating a release

### ISSUE THREAD

**Issue by montefra** [ericmandel/xpa#1]
Following [these instructions](https://help.github.com/articles/creating-releases/) it's possible to make the release more appealing and to add some info about.

I've done for the [v1.8 pyds9 release](https://github.com/ericmandel/pyds9/releases) and it looks much nicer that a simple tag number :blush:

**Comment by ericmandel** [comment]
Very nice, @montefra, thanks for pointing this out. I'll use it for the upcoming js9 release!

**Comment by ericmandel** [comment]
@montefra I'm confused ... a release was created as soon as I tagged xpa with v2.1.17. So am I **not** supposed to add a version tag first? Does these release instructions create the tag??

**Comment by montefra** [comment]
Once you create a tag github creates a release for you. On there release page there should be two buttons: "Releases" and "Tags". If you click on "Tabs" you should have the list of tabs and for each of them there should be a link about creating releases notes. If you click on it you should get and editor like the one for issues. If you fill and save it you should get the nicely formatted info as we have in pyds9.

The link I gave you is about creating a release and a tag at the same time. Sorry for the confusion
