### ISSUE TITLE
shared libs ignore LDFLAGS

### ISSUE THREAD

**Issue by beckermr** [ericmandel/xpa#10]
Currently the shared library build ignores LDFLAGS. This patch will fix it

```
--- a/Makefile.in
+++ b/Makefile.in
@@ -182,7 +182,7 @@
 		rm -f lib$(PACKAGE).tmp/xt*.o; \
 		rm -f lib$(PACKAGE).tmp/tcl*.o; \
 		CC='$(CC)' CXX=$(CXX) \
-		./mklib -o $(PACKAGE) lib$(PACKAGE).tmp/*.o; \
+		./mklib -ldflags "$(LDFLAGS)" -o $(PACKAGE) lib$(PACKAGE).tmp/*.o; \
 		rm -rf lib$(PACKAGE).tmp)

 mingw-dll:	$(LIBOBJS)
```

**Comment by ericmandel** [comment]
Thanks! All updated in GitHub ...

**Comment by beckermr** [comment]
BTW, I pushed this to conda-forge. https://github.com/conda-forge/xpa-feedstock

Ping me on the repo above if you want to help maintain it.

**Comment by ericmandel** [comment]
Thanks, I'm happy to have you maintain it there ... but let me know if you run into other problems (shouldn't be too many after 20 years, other than the fact that it's time to replace it entirely.)

**Comment by beckermr** [comment]
Sounds good. I had to add some patches to point the `mklib` at the conda-forge linkers etc. I am happy to submit them here, but they can also live in the conda repo. Thanks!

**Comment by ericmandel** [comment]
Probably make my life easier if you just keep them on the conda repo ... thanks ...
