### ISSUE TITLE
Wrong tag (?)

### ISSUE THREAD

**Issue by olebole** [ericmandel/xpa#2]
Hi,

the latest version is tagged as 2.1.6; the previous one (that was on http://hea-www.harvard.edu/saord/download/xpa/) was however 2.1.15.

Maybe this is a spelling errror and should be 2.1.**16** instead of 2.1.**6**?

**Comment by ericmandel** [comment]
@olebole Yes, that was a typo, now fixed. Thanks for pointing it out.
