### ISSUE TITLE
compiling with strict POSIX standards

### ISSUE THREAD

**Issue by ntessore** [ericmandel/xpa#3]
It seems that the POSIX.1-2001 standard requires a different/additional header file `<sys/select.h>` to be included to provide the `fd_set` type. See for example [here](http://linux.die.net/man/3/fd_set) and [here](http://pubs.opengroup.org/onlinepubs/009696899/basedefs/sys/select.h.html). The error when compiling with strict standard settings is

```
xpa-master/xpa.h:403:33: error: unknown type name 'fd_set'
int XPAAddSelect _PRx((XPA xpa, fd_set *readfdsptr));
                                ^
xpa-master/prsetup.h:27:17: note: expanded from macro '_PRx'
#define _PRx(s) s
                ^
```

In order to use XPA on a Linux system in a `--std=c99` code, I had to use the following:

``` c
#define _XOPEN_SOURCE 600
#include <sys/select.h>
#include "xpa.h"
```

**Comment by ericmandel** [comment]
@ntessore on my Linux box (2.6.32-573.3.1.el6.x86_64 #1 SMP), this set of gcc 4.9 switches builds xpa successfully without the need to include sys/select.h:

```
gcc --std=c99 -D_XOPEN_SOURCE
```

And these also work:

```
gcc --std=c99 -D_XOPEN_SOURCE=400
gcc --std=c99 -D_XOPEN_SOURCE=600
gcc --std=c99 -D_XOPEN_SOURCE=700
```

Can you please try this on your system? if it works, I could check for --std=c99 at configure time and add -D_XOPEN_SOURCE automatically ... but do you think this is something that should be decided by the builder?

**Comment by ntessore** [comment]
This is interesting. I run into this problem when building on Travis CI, which runs Ubuntu 12.04.5 LTS.
I made a primitive [test project](https://github.com/ntessore/xpatest) and you can find a build across a range of compilers [here](https://travis-ci.org/ntessore/xpatest/builds/109068770).
Am I overlooking something simple?

**Comment by ntessore** [comment]
PS:  Might it be an issue of eglibc on Debian/Ubuntu vs glibc on Redhat/Fedora?

```
$ ldd --version
ldd (Ubuntu EGLIBC 2.15-0ubuntu10.10) 2.15
```

**Comment by ericmandel** [comment]
@ntessore Sigh ... it could be anything ... so why don't I arrange for configure to test for sys/select.h and include it if present on the system. That's easy and should be done in a few minutes.

But the -D_XOPEN_SOURCE is more problematic. It seems to me that if you add the --std-c99 switch to CFLAGS, you should also explicitly choose one of the -D_XOPEN_SOURCE defines as well.  Would that work for you?

**Comment by ericmandel** [comment]
@ntessore I added the include of sys/select.h on systems where its present. The code compiles fine on OS X and my CentOS Linux, using both c99 and "normal" gcc ... and also seems to work. Its updated in the respository.

Can you give it a try and let me know? The we can discuss what to do about _XOPEN_SOURCE.

**Comment by ericmandel** [comment]
I also got rid of all warnings except the ones requiring definition of _BSD_SOURCE when --std=c99 is used. An good explanation  is here:

http://stackoverflow.com/questions/3355298/unistd-h-and-c99-on-linux

More and more, it looks like use of c99 requires the builder to know something. Not sure what to do ...

**Comment by ntessore** [comment]
Building XPA with the stricter standard appears to work for me as well without problems.

However, maybe the situation is more simple than I have understood at first. When using the programmatic interface, XPA did not work with my `-std=c99` code for the same reason. Defining _XOPEN_SOURCE and including sys/select.h before XPA makes the API work even if XPA was compiled with different settings. Maybe it would suffice in xpa.h to warn if _POSIX_C_SOURCE is not set, and include sys/select.h if _POSIX_C_SOURCE >= 200112L is set?

**Comment by ericmandel** [comment]
Good thought ... we could check for POSIX_C_SOURCE >= 200112L and include sys/select.h in that case. But that might be too restrictive: I see that OS X does not define POSIX_C_SOURCE but still wants you to include sys/select.h in order to call select(). (The reason why the old XPA code compiled at all is that unistd.h loads sys/select.h as a silent work-around!) 

Loading the old-style (sys/time.h, sys/types.h, unistd.h)  and the new style (sys/select.h) doesn't seem to result in any "duplicate" warnings, while covering all bases. Any serious objection to leaving it that way?

**Comment by ntessore** [comment]
No objections there, it seems to be the most sane way. Thanks for looking into this!
