### ISSUE TITLE
xpamb doc mentions -store; should be -data

### ISSUE THREAD

**Issue by djerius** [ericmandel/xpa#7]
under **OPTIONS**, just after the documentation for **-del**, there's an example:

`cat foo.fits | xpaset xpamb -store foo -info "FITS" "DS9:*" fits foo.fits`

That should be

`cat foo.fits | xpaset xpamb -data foo -info "FITS" "DS9:*" fits foo.fits`

**Comment by ericmandel** [comment]
Thanks, Diab, I fixed the documentation (in two places, plus a typo).
