### ISSUE TITLE
uintptr_t undeclared error on Fedora >= 27

### ISSUE THREAD

**Issue by sergiopasra** [ericmandel/xpa#8]
Hello, when compiling xpa with TCL support in a Fedora >= 27 system, I get the following error

tcl.c: In function 'XPARec_Tcl':
tcl.c:974:58: error: 'uintptr_t' undeclared (first use in this function); did you mean 'intptr_t'?

       if( !(chan = Tcl_MakeTcpClientChannel((ClientData)(uintptr_t)xpa_cmdfd(xpa))) ){
                                                          ^~~~~~~~~
                                                           intptr_t

The compilation worked in Fedora 26.

The problem appears when compiling in the Fedora build system, that is, where the RPMS for Fedora are created. The CFLAGS hare are set to 

CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables'

If I patch tcl.c to include <stdint.h>, the error goes away, but I don't know if this will work generally or only for Fedoras

**Comment by ericmandel** [comment]
@sergiopasra It looks like <stdint.h> was added to xpap.h in January. Can you pull the latest code and see if that works for you?
````
commit 24e96b7ac19ca79869ec2cd5d12dcf728c891c13
Author: Eric Mandel <eric@cfa.harvard.edu>
Date:   Mon Jan 22 16:43:46 2018 -0500

    add stdint.h to xpap.h, if present
````

**Comment by sergiopasra** [comment]
@ericmandel Yes, if I use that commit as a patch it compiles

**Comment by ericmandel** [comment]
OK, then I think we can close this issue.
